/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as ApplicationCompleteRouteImport } from './routes/application-complete'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes/_authenticated/portal/route'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as ApplicationCompleteUnlicensedTokenRouteImport } from './routes/application-complete/unlicensed.$token'
import { Route as ApplicationCompleteLicensedTokenRouteImport } from './routes/application-complete/licensed.$token'
import { Route as AuthenticatedPortalTasksRouteImport } from './routes/_authenticated/portal/tasks'
import { Route as AuthenticatedPortalSettingsRouteImport } from './routes/_authenticated/portal/settings'
import { Route as AuthenticatedPortalPipelineRouteImport } from './routes/_authenticated/portal/pipeline'
import { Route as AuthenticatedPortalLeaderboardRouteImport } from './routes/_authenticated/portal/leaderboard'
import { Route as AuthenticatedPortalCalendarRouteImport } from './routes/_authenticated/portal/calendar'
import { Route as AuthenticatedPortalResourcesRouteRouteImport } from './routes/_authenticated/portal/resources/route'
import { Route as AuthenticatedPortalCrmRouteRouteImport } from './routes/_authenticated/portal/crm/route'
import { Route as AuthenticatedPortalAdminRouteRouteImport } from './routes/_authenticated/portal/admin/route'
import { Route as AuthenticatedPortalResourcesIndexRouteImport } from './routes/_authenticated/portal/resources/index'
import { Route as AuthenticatedPortalCrmIndexRouteImport } from './routes/_authenticated/portal/crm/index'
import { Route as AuthenticatedPortalAdminIndexRouteImport } from './routes/_authenticated/portal/admin/index'
import { Route as ApiPublicWebhooksCalendlyRouteImport } from './routes/api/public/webhooks/calendly'
import { Route as AuthenticatedPortalResourcesPresentationsRouteImport } from './routes/_authenticated/portal/resources/presentations'
import { Route as AuthenticatedPortalResourcesLibraryRouteImport } from './routes/_authenticated/portal/resources/library'
import { Route as AuthenticatedPortalResourcesAdminRouteImport } from './routes/_authenticated/portal/resources/admin'
import { Route as AuthenticatedPortalCrmApplicantIdRouteImport } from './routes/_authenticated/portal/crm/$applicantId'
import { Route as AuthenticatedPortalAdminUsersRouteImport } from './routes/_authenticated/portal/admin/users'
import { Route as AuthenticatedPortalAdminStagesRouteImport } from './routes/_authenticated/portal/admin/stages'
import { Route as AuthenticatedPortalAdminSettingsRouteImport } from './routes/_authenticated/portal/admin/settings'

const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationCompleteRoute = ApplicationCompleteRouteImport.update({
  id: '/application-complete',
  path: '/application-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const ApplicationCompleteUnlicensedTokenRoute =
  ApplicationCompleteUnlicensedTokenRouteImport.update({
    id: '/unlicensed/$token',
    path: '/unlicensed/$token',
    getParentRoute: () => ApplicationCompleteRoute,
  } as any)
const ApplicationCompleteLicensedTokenRoute =
  ApplicationCompleteLicensedTokenRouteImport.update({
    id: '/licensed/$token',
    path: '/licensed/$token',
    getParentRoute: () => ApplicationCompleteRoute,
  } as any)
const AuthenticatedPortalTasksRoute =
  AuthenticatedPortalTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalSettingsRoute =
  AuthenticatedPortalSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalPipelineRoute =
  AuthenticatedPortalPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalLeaderboardRoute =
  AuthenticatedPortalLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalCalendarRoute =
  AuthenticatedPortalCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalResourcesRouteRoute =
  AuthenticatedPortalResourcesRouteRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalCrmRouteRoute =
  AuthenticatedPortalCrmRouteRouteImport.update({
    id: '/crm',
    path: '/crm',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalAdminRouteRoute =
  AuthenticatedPortalAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalResourcesIndexRoute =
  AuthenticatedPortalResourcesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalResourcesRouteRoute,
  } as any)
const AuthenticatedPortalCrmIndexRoute =
  AuthenticatedPortalCrmIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalCrmRouteRoute,
  } as any)
const AuthenticatedPortalAdminIndexRoute =
  AuthenticatedPortalAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalAdminRouteRoute,
  } as any)
const ApiPublicWebhooksCalendlyRoute =
  ApiPublicWebhooksCalendlyRouteImport.update({
    id: '/api/public/webhooks/calendly',
    path: '/api/public/webhooks/calendly',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPortalResourcesPresentationsRoute =
  AuthenticatedPortalResourcesPresentationsRouteImport.update({
    id: '/presentations',
    path: '/presentations',
    getParentRoute: () => AuthenticatedPortalResourcesRouteRoute,
  } as any)
const AuthenticatedPortalResourcesLibraryRoute =
  AuthenticatedPortalResourcesLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedPortalResourcesRouteRoute,
  } as any)
const AuthenticatedPortalResourcesAdminRoute =
  AuthenticatedPortalResourcesAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedPortalResourcesRouteRoute,
  } as any)
const AuthenticatedPortalCrmApplicantIdRoute =
  AuthenticatedPortalCrmApplicantIdRouteImport.update({
    id: '/$applicantId',
    path: '/$applicantId',
    getParentRoute: () => AuthenticatedPortalCrmRouteRoute,
  } as any)
const AuthenticatedPortalAdminUsersRoute =
  AuthenticatedPortalAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedPortalAdminRouteRoute,
  } as any)
const AuthenticatedPortalAdminStagesRoute =
  AuthenticatedPortalAdminStagesRouteImport.update({
    id: '/stages',
    path: '/stages',
    getParentRoute: () => AuthenticatedPortalAdminRouteRoute,
  } as any)
const AuthenticatedPortalAdminSettingsRoute =
  AuthenticatedPortalAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedPortalAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/application-complete': typeof ApplicationCompleteRouteWithChildren
  '/apply': typeof ApplyRoute
  '/evaluation': typeof EvaluationRoute
  '/login': typeof LoginRoute
  '/schedule': typeof ScheduleRoute
  '/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/portal/admin': typeof AuthenticatedPortalAdminRouteRouteWithChildren
  '/portal/crm': typeof AuthenticatedPortalCrmRouteRouteWithChildren
  '/portal/resources': typeof AuthenticatedPortalResourcesRouteRouteWithChildren
  '/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/portal/leaderboard': typeof AuthenticatedPortalLeaderboardRoute
  '/portal/pipeline': typeof AuthenticatedPortalPipelineRoute
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/portal/tasks': typeof AuthenticatedPortalTasksRoute
  '/application-complete/licensed/$token': typeof ApplicationCompleteLicensedTokenRoute
  '/application-complete/unlicensed/$token': typeof ApplicationCompleteUnlicensedTokenRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/portal/admin/settings': typeof AuthenticatedPortalAdminSettingsRoute
  '/portal/admin/stages': typeof AuthenticatedPortalAdminStagesRoute
  '/portal/admin/users': typeof AuthenticatedPortalAdminUsersRoute
  '/portal/crm/$applicantId': typeof AuthenticatedPortalCrmApplicantIdRoute
  '/portal/resources/admin': typeof AuthenticatedPortalResourcesAdminRoute
  '/portal/resources/library': typeof AuthenticatedPortalResourcesLibraryRoute
  '/portal/resources/presentations': typeof AuthenticatedPortalResourcesPresentationsRoute
  '/api/public/webhooks/calendly': typeof ApiPublicWebhooksCalendlyRoute
  '/portal/admin/': typeof AuthenticatedPortalAdminIndexRoute
  '/portal/crm/': typeof AuthenticatedPortalCrmIndexRoute
  '/portal/resources/': typeof AuthenticatedPortalResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/application-complete': typeof ApplicationCompleteRouteWithChildren
  '/apply': typeof ApplyRoute
  '/evaluation': typeof EvaluationRoute
  '/login': typeof LoginRoute
  '/schedule': typeof ScheduleRoute
  '/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/portal/leaderboard': typeof AuthenticatedPortalLeaderboardRoute
  '/portal/pipeline': typeof AuthenticatedPortalPipelineRoute
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/portal/tasks': typeof AuthenticatedPortalTasksRoute
  '/application-complete/licensed/$token': typeof ApplicationCompleteLicensedTokenRoute
  '/application-complete/unlicensed/$token': typeof ApplicationCompleteUnlicensedTokenRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/portal/admin/settings': typeof AuthenticatedPortalAdminSettingsRoute
  '/portal/admin/stages': typeof AuthenticatedPortalAdminStagesRoute
  '/portal/admin/users': typeof AuthenticatedPortalAdminUsersRoute
  '/portal/crm/$applicantId': typeof AuthenticatedPortalCrmApplicantIdRoute
  '/portal/resources/admin': typeof AuthenticatedPortalResourcesAdminRoute
  '/portal/resources/library': typeof AuthenticatedPortalResourcesLibraryRoute
  '/portal/resources/presentations': typeof AuthenticatedPortalResourcesPresentationsRoute
  '/api/public/webhooks/calendly': typeof ApiPublicWebhooksCalendlyRoute
  '/portal/admin': typeof AuthenticatedPortalAdminIndexRoute
  '/portal/crm': typeof AuthenticatedPortalCrmIndexRoute
  '/portal/resources': typeof AuthenticatedPortalResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/application-complete': typeof ApplicationCompleteRouteWithChildren
  '/apply': typeof ApplyRoute
  '/evaluation': typeof EvaluationRoute
  '/login': typeof LoginRoute
  '/schedule': typeof ScheduleRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/_authenticated/portal/admin': typeof AuthenticatedPortalAdminRouteRouteWithChildren
  '/_authenticated/portal/crm': typeof AuthenticatedPortalCrmRouteRouteWithChildren
  '/_authenticated/portal/resources': typeof AuthenticatedPortalResourcesRouteRouteWithChildren
  '/_authenticated/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/_authenticated/portal/leaderboard': typeof AuthenticatedPortalLeaderboardRoute
  '/_authenticated/portal/pipeline': typeof AuthenticatedPortalPipelineRoute
  '/_authenticated/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/_authenticated/portal/tasks': typeof AuthenticatedPortalTasksRoute
  '/application-complete/licensed/$token': typeof ApplicationCompleteLicensedTokenRoute
  '/application-complete/unlicensed/$token': typeof ApplicationCompleteUnlicensedTokenRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/portal/admin/settings': typeof AuthenticatedPortalAdminSettingsRoute
  '/_authenticated/portal/admin/stages': typeof AuthenticatedPortalAdminStagesRoute
  '/_authenticated/portal/admin/users': typeof AuthenticatedPortalAdminUsersRoute
  '/_authenticated/portal/crm/$applicantId': typeof AuthenticatedPortalCrmApplicantIdRoute
  '/_authenticated/portal/resources/admin': typeof AuthenticatedPortalResourcesAdminRoute
  '/_authenticated/portal/resources/library': typeof AuthenticatedPortalResourcesLibraryRoute
  '/_authenticated/portal/resources/presentations': typeof AuthenticatedPortalResourcesPresentationsRoute
  '/api/public/webhooks/calendly': typeof ApiPublicWebhooksCalendlyRoute
  '/_authenticated/portal/admin/': typeof AuthenticatedPortalAdminIndexRoute
  '/_authenticated/portal/crm/': typeof AuthenticatedPortalCrmIndexRoute
  '/_authenticated/portal/resources/': typeof AuthenticatedPortalResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/application-complete'
    | '/apply'
    | '/evaluation'
    | '/login'
    | '/schedule'
    | '/portal'
    | '/portal/admin'
    | '/portal/crm'
    | '/portal/resources'
    | '/portal/calendar'
    | '/portal/leaderboard'
    | '/portal/pipeline'
    | '/portal/settings'
    | '/portal/tasks'
    | '/application-complete/licensed/$token'
    | '/application-complete/unlicensed/$token'
    | '/portal/'
    | '/portal/admin/settings'
    | '/portal/admin/stages'
    | '/portal/admin/users'
    | '/portal/crm/$applicantId'
    | '/portal/resources/admin'
    | '/portal/resources/library'
    | '/portal/resources/presentations'
    | '/api/public/webhooks/calendly'
    | '/portal/admin/'
    | '/portal/crm/'
    | '/portal/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/application-complete'
    | '/apply'
    | '/evaluation'
    | '/login'
    | '/schedule'
    | '/portal/calendar'
    | '/portal/leaderboard'
    | '/portal/pipeline'
    | '/portal/settings'
    | '/portal/tasks'
    | '/application-complete/licensed/$token'
    | '/application-complete/unlicensed/$token'
    | '/portal'
    | '/portal/admin/settings'
    | '/portal/admin/stages'
    | '/portal/admin/users'
    | '/portal/crm/$applicantId'
    | '/portal/resources/admin'
    | '/portal/resources/library'
    | '/portal/resources/presentations'
    | '/api/public/webhooks/calendly'
    | '/portal/admin'
    | '/portal/crm'
    | '/portal/resources'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/application-complete'
    | '/apply'
    | '/evaluation'
    | '/login'
    | '/schedule'
    | '/_authenticated/portal'
    | '/_authenticated/portal/admin'
    | '/_authenticated/portal/crm'
    | '/_authenticated/portal/resources'
    | '/_authenticated/portal/calendar'
    | '/_authenticated/portal/leaderboard'
    | '/_authenticated/portal/pipeline'
    | '/_authenticated/portal/settings'
    | '/_authenticated/portal/tasks'
    | '/application-complete/licensed/$token'
    | '/application-complete/unlicensed/$token'
    | '/_authenticated/portal/'
    | '/_authenticated/portal/admin/settings'
    | '/_authenticated/portal/admin/stages'
    | '/_authenticated/portal/admin/users'
    | '/_authenticated/portal/crm/$applicantId'
    | '/_authenticated/portal/resources/admin'
    | '/_authenticated/portal/resources/library'
    | '/_authenticated/portal/resources/presentations'
    | '/api/public/webhooks/calendly'
    | '/_authenticated/portal/admin/'
    | '/_authenticated/portal/crm/'
    | '/_authenticated/portal/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApplicationCompleteRoute: typeof ApplicationCompleteRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  EvaluationRoute: typeof EvaluationRoute
  LoginRoute: typeof LoginRoute
  ScheduleRoute: typeof ScheduleRoute
  ApiPublicWebhooksCalendlyRoute: typeof ApiPublicWebhooksCalendlyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-complete': {
      id: '/application-complete'
      path: '/application-complete'
      fullPath: '/application-complete'
      preLoaderRoute: typeof ApplicationCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/application-complete/unlicensed/$token': {
      id: '/application-complete/unlicensed/$token'
      path: '/unlicensed/$token'
      fullPath: '/application-complete/unlicensed/$token'
      preLoaderRoute: typeof ApplicationCompleteUnlicensedTokenRouteImport
      parentRoute: typeof ApplicationCompleteRoute
    }
    '/application-complete/licensed/$token': {
      id: '/application-complete/licensed/$token'
      path: '/licensed/$token'
      fullPath: '/application-complete/licensed/$token'
      preLoaderRoute: typeof ApplicationCompleteLicensedTokenRouteImport
      parentRoute: typeof ApplicationCompleteRoute
    }
    '/_authenticated/portal/tasks': {
      id: '/_authenticated/portal/tasks'
      path: '/tasks'
      fullPath: '/portal/tasks'
      preLoaderRoute: typeof AuthenticatedPortalTasksRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/settings': {
      id: '/_authenticated/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof AuthenticatedPortalSettingsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/pipeline': {
      id: '/_authenticated/portal/pipeline'
      path: '/pipeline'
      fullPath: '/portal/pipeline'
      preLoaderRoute: typeof AuthenticatedPortalPipelineRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/leaderboard': {
      id: '/_authenticated/portal/leaderboard'
      path: '/leaderboard'
      fullPath: '/portal/leaderboard'
      preLoaderRoute: typeof AuthenticatedPortalLeaderboardRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/calendar': {
      id: '/_authenticated/portal/calendar'
      path: '/calendar'
      fullPath: '/portal/calendar'
      preLoaderRoute: typeof AuthenticatedPortalCalendarRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/resources': {
      id: '/_authenticated/portal/resources'
      path: '/resources'
      fullPath: '/portal/resources'
      preLoaderRoute: typeof AuthenticatedPortalResourcesRouteRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/crm': {
      id: '/_authenticated/portal/crm'
      path: '/crm'
      fullPath: '/portal/crm'
      preLoaderRoute: typeof AuthenticatedPortalCrmRouteRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/admin': {
      id: '/_authenticated/portal/admin'
      path: '/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof AuthenticatedPortalAdminRouteRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/resources/': {
      id: '/_authenticated/portal/resources/'
      path: '/'
      fullPath: '/portal/resources/'
      preLoaderRoute: typeof AuthenticatedPortalResourcesIndexRouteImport
      parentRoute: typeof AuthenticatedPortalResourcesRouteRoute
    }
    '/_authenticated/portal/crm/': {
      id: '/_authenticated/portal/crm/'
      path: '/'
      fullPath: '/portal/crm/'
      preLoaderRoute: typeof AuthenticatedPortalCrmIndexRouteImport
      parentRoute: typeof AuthenticatedPortalCrmRouteRoute
    }
    '/_authenticated/portal/admin/': {
      id: '/_authenticated/portal/admin/'
      path: '/'
      fullPath: '/portal/admin/'
      preLoaderRoute: typeof AuthenticatedPortalAdminIndexRouteImport
      parentRoute: typeof AuthenticatedPortalAdminRouteRoute
    }
    '/api/public/webhooks/calendly': {
      id: '/api/public/webhooks/calendly'
      path: '/api/public/webhooks/calendly'
      fullPath: '/api/public/webhooks/calendly'
      preLoaderRoute: typeof ApiPublicWebhooksCalendlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/resources/presentations': {
      id: '/_authenticated/portal/resources/presentations'
      path: '/presentations'
      fullPath: '/portal/resources/presentations'
      preLoaderRoute: typeof AuthenticatedPortalResourcesPresentationsRouteImport
      parentRoute: typeof AuthenticatedPortalResourcesRouteRoute
    }
    '/_authenticated/portal/resources/library': {
      id: '/_authenticated/portal/resources/library'
      path: '/library'
      fullPath: '/portal/resources/library'
      preLoaderRoute: typeof AuthenticatedPortalResourcesLibraryRouteImport
      parentRoute: typeof AuthenticatedPortalResourcesRouteRoute
    }
    '/_authenticated/portal/resources/admin': {
      id: '/_authenticated/portal/resources/admin'
      path: '/admin'
      fullPath: '/portal/resources/admin'
      preLoaderRoute: typeof AuthenticatedPortalResourcesAdminRouteImport
      parentRoute: typeof AuthenticatedPortalResourcesRouteRoute
    }
    '/_authenticated/portal/crm/$applicantId': {
      id: '/_authenticated/portal/crm/$applicantId'
      path: '/$applicantId'
      fullPath: '/portal/crm/$applicantId'
      preLoaderRoute: typeof AuthenticatedPortalCrmApplicantIdRouteImport
      parentRoute: typeof AuthenticatedPortalCrmRouteRoute
    }
    '/_authenticated/portal/admin/users': {
      id: '/_authenticated/portal/admin/users'
      path: '/users'
      fullPath: '/portal/admin/users'
      preLoaderRoute: typeof AuthenticatedPortalAdminUsersRouteImport
      parentRoute: typeof AuthenticatedPortalAdminRouteRoute
    }
    '/_authenticated/portal/admin/stages': {
      id: '/_authenticated/portal/admin/stages'
      path: '/stages'
      fullPath: '/portal/admin/stages'
      preLoaderRoute: typeof AuthenticatedPortalAdminStagesRouteImport
      parentRoute: typeof AuthenticatedPortalAdminRouteRoute
    }
    '/_authenticated/portal/admin/settings': {
      id: '/_authenticated/portal/admin/settings'
      path: '/settings'
      fullPath: '/portal/admin/settings'
      preLoaderRoute: typeof AuthenticatedPortalAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedPortalAdminRouteRoute
    }
  }
}

interface AuthenticatedPortalAdminRouteRouteChildren {
  AuthenticatedPortalAdminSettingsRoute: typeof AuthenticatedPortalAdminSettingsRoute
  AuthenticatedPortalAdminStagesRoute: typeof AuthenticatedPortalAdminStagesRoute
  AuthenticatedPortalAdminUsersRoute: typeof AuthenticatedPortalAdminUsersRoute
  AuthenticatedPortalAdminIndexRoute: typeof AuthenticatedPortalAdminIndexRoute
}

const AuthenticatedPortalAdminRouteRouteChildren: AuthenticatedPortalAdminRouteRouteChildren =
  {
    AuthenticatedPortalAdminSettingsRoute:
      AuthenticatedPortalAdminSettingsRoute,
    AuthenticatedPortalAdminStagesRoute: AuthenticatedPortalAdminStagesRoute,
    AuthenticatedPortalAdminUsersRoute: AuthenticatedPortalAdminUsersRoute,
    AuthenticatedPortalAdminIndexRoute: AuthenticatedPortalAdminIndexRoute,
  }

const AuthenticatedPortalAdminRouteRouteWithChildren =
  AuthenticatedPortalAdminRouteRoute._addFileChildren(
    AuthenticatedPortalAdminRouteRouteChildren,
  )

interface AuthenticatedPortalCrmRouteRouteChildren {
  AuthenticatedPortalCrmApplicantIdRoute: typeof AuthenticatedPortalCrmApplicantIdRoute
  AuthenticatedPortalCrmIndexRoute: typeof AuthenticatedPortalCrmIndexRoute
}

const AuthenticatedPortalCrmRouteRouteChildren: AuthenticatedPortalCrmRouteRouteChildren =
  {
    AuthenticatedPortalCrmApplicantIdRoute:
      AuthenticatedPortalCrmApplicantIdRoute,
    AuthenticatedPortalCrmIndexRoute: AuthenticatedPortalCrmIndexRoute,
  }

const AuthenticatedPortalCrmRouteRouteWithChildren =
  AuthenticatedPortalCrmRouteRoute._addFileChildren(
    AuthenticatedPortalCrmRouteRouteChildren,
  )

interface AuthenticatedPortalResourcesRouteRouteChildren {
  AuthenticatedPortalResourcesAdminRoute: typeof AuthenticatedPortalResourcesAdminRoute
  AuthenticatedPortalResourcesLibraryRoute: typeof AuthenticatedPortalResourcesLibraryRoute
  AuthenticatedPortalResourcesPresentationsRoute: typeof AuthenticatedPortalResourcesPresentationsRoute
  AuthenticatedPortalResourcesIndexRoute: typeof AuthenticatedPortalResourcesIndexRoute
}

const AuthenticatedPortalResourcesRouteRouteChildren: AuthenticatedPortalResourcesRouteRouteChildren =
  {
    AuthenticatedPortalResourcesAdminRoute:
      AuthenticatedPortalResourcesAdminRoute,
    AuthenticatedPortalResourcesLibraryRoute:
      AuthenticatedPortalResourcesLibraryRoute,
    AuthenticatedPortalResourcesPresentationsRoute:
      AuthenticatedPortalResourcesPresentationsRoute,
    AuthenticatedPortalResourcesIndexRoute:
      AuthenticatedPortalResourcesIndexRoute,
  }

const AuthenticatedPortalResourcesRouteRouteWithChildren =
  AuthenticatedPortalResourcesRouteRoute._addFileChildren(
    AuthenticatedPortalResourcesRouteRouteChildren,
  )

interface AuthenticatedPortalRouteRouteChildren {
  AuthenticatedPortalAdminRouteRoute: typeof AuthenticatedPortalAdminRouteRouteWithChildren
  AuthenticatedPortalCrmRouteRoute: typeof AuthenticatedPortalCrmRouteRouteWithChildren
  AuthenticatedPortalResourcesRouteRoute: typeof AuthenticatedPortalResourcesRouteRouteWithChildren
  AuthenticatedPortalCalendarRoute: typeof AuthenticatedPortalCalendarRoute
  AuthenticatedPortalLeaderboardRoute: typeof AuthenticatedPortalLeaderboardRoute
  AuthenticatedPortalPipelineRoute: typeof AuthenticatedPortalPipelineRoute
  AuthenticatedPortalSettingsRoute: typeof AuthenticatedPortalSettingsRoute
  AuthenticatedPortalTasksRoute: typeof AuthenticatedPortalTasksRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteRouteChildren: AuthenticatedPortalRouteRouteChildren =
  {
    AuthenticatedPortalAdminRouteRoute:
      AuthenticatedPortalAdminRouteRouteWithChildren,
    AuthenticatedPortalCrmRouteRoute:
      AuthenticatedPortalCrmRouteRouteWithChildren,
    AuthenticatedPortalResourcesRouteRoute:
      AuthenticatedPortalResourcesRouteRouteWithChildren,
    AuthenticatedPortalCalendarRoute: AuthenticatedPortalCalendarRoute,
    AuthenticatedPortalLeaderboardRoute: AuthenticatedPortalLeaderboardRoute,
    AuthenticatedPortalPipelineRoute: AuthenticatedPortalPipelineRoute,
    AuthenticatedPortalSettingsRoute: AuthenticatedPortalSettingsRoute,
    AuthenticatedPortalTasksRoute: AuthenticatedPortalTasksRoute,
    AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  }

const AuthenticatedPortalRouteRouteWithChildren =
  AuthenticatedPortalRouteRoute._addFileChildren(
    AuthenticatedPortalRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalRouteRoute: typeof AuthenticatedPortalRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalRouteRoute: AuthenticatedPortalRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApplicationCompleteRouteChildren {
  ApplicationCompleteLicensedTokenRoute: typeof ApplicationCompleteLicensedTokenRoute
  ApplicationCompleteUnlicensedTokenRoute: typeof ApplicationCompleteUnlicensedTokenRoute
}

const ApplicationCompleteRouteChildren: ApplicationCompleteRouteChildren = {
  ApplicationCompleteLicensedTokenRoute: ApplicationCompleteLicensedTokenRoute,
  ApplicationCompleteUnlicensedTokenRoute:
    ApplicationCompleteUnlicensedTokenRoute,
}

const ApplicationCompleteRouteWithChildren =
  ApplicationCompleteRoute._addFileChildren(ApplicationCompleteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApplicationCompleteRoute: ApplicationCompleteRouteWithChildren,
  ApplyRoute: ApplyRoute,
  EvaluationRoute: EvaluationRoute,
  LoginRoute: LoginRoute,
  ScheduleRoute: ScheduleRoute,
  ApiPublicWebhooksCalendlyRoute: ApiPublicWebhooksCalendlyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
