/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as ApplicationCompleteRouteImport } from './routes/application-complete'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes/_authenticated/portal/route'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedPortalTasksRouteImport } from './routes/_authenticated/portal/tasks'
import { Route as AuthenticatedPortalResourcesRouteImport } from './routes/_authenticated/portal/resources'
import { Route as AuthenticatedPortalPipelineRouteImport } from './routes/_authenticated/portal/pipeline'
import { Route as AuthenticatedPortalLeaderboardRouteImport } from './routes/_authenticated/portal/leaderboard'
import { Route as AuthenticatedPortalCalendarRouteImport } from './routes/_authenticated/portal/calendar'
import { Route as AuthenticatedPortalCrmRouteRouteImport } from './routes/_authenticated/portal/crm/route'
import { Route as AuthenticatedPortalAdminRouteRouteImport } from './routes/_authenticated/portal/admin/route'
import { Route as AuthenticatedPortalCrmIndexRouteImport } from './routes/_authenticated/portal/crm/index'
import { Route as AuthenticatedPortalAdminIndexRouteImport } from './routes/_authenticated/portal/admin/index'
import { Route as AuthenticatedPortalCrmApplicantIdRouteImport } from './routes/_authenticated/portal/crm/$applicantId'
import { Route as AuthenticatedPortalAdminUsersRouteImport } from './routes/_authenticated/portal/admin/users'
import { Route as AuthenticatedPortalAdminStagesRouteImport } from './routes/_authenticated/portal/admin/stages'
import { Route as AuthenticatedPortalAdminSettingsRouteImport } from './routes/_authenticated/portal/admin/settings'

const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationCompleteRoute = ApplicationCompleteRouteImport.update({
  id: '/application-complete',
  path: '/application-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalTasksRoute =
  AuthenticatedPortalTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalResourcesRoute =
  AuthenticatedPortalResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalPipelineRoute =
  AuthenticatedPortalPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalLeaderboardRoute =
  AuthenticatedPortalLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalCalendarRoute =
  AuthenticatedPortalCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalCrmRouteRoute =
  AuthenticatedPortalCrmRouteRouteImport.update({
    id: '/crm',
    path: '/crm',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalAdminRouteRoute =
  AuthenticatedPortalAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalCrmIndexRoute =
  AuthenticatedPortalCrmIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalCrmRouteRoute,
  } as any)
const AuthenticatedPortalAdminIndexRoute =
  AuthenticatedPortalAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalAdminRouteRoute,
  } as any)
const AuthenticatedPortalCrmApplicantIdRoute =
  AuthenticatedPortalCrmApplicantIdRouteImport.update({
    id: '/$applicantId',
    path: '/$applicantId',
    getParentRoute: () => AuthenticatedPortalCrmRouteRoute,
  } as any)
const AuthenticatedPortalAdminUsersRoute =
  AuthenticatedPortalAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedPortalAdminRouteRoute,
  } as any)
const AuthenticatedPortalAdminStagesRoute =
  AuthenticatedPortalAdminStagesRouteImport.update({
    id: '/stages',
    path: '/stages',
    getParentRoute: () => AuthenticatedPortalAdminRouteRoute,
  } as any)
const AuthenticatedPortalAdminSettingsRoute =
  AuthenticatedPortalAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedPortalAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/application-complete': typeof ApplicationCompleteRoute
  '/apply': typeof ApplyRoute
  '/evaluation': typeof EvaluationRoute
  '/login': typeof LoginRoute
  '/schedule': typeof ScheduleRoute
  '/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/portal/admin': typeof AuthenticatedPortalAdminRouteRouteWithChildren
  '/portal/crm': typeof AuthenticatedPortalCrmRouteRouteWithChildren
  '/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/portal/leaderboard': typeof AuthenticatedPortalLeaderboardRoute
  '/portal/pipeline': typeof AuthenticatedPortalPipelineRoute
  '/portal/resources': typeof AuthenticatedPortalResourcesRoute
  '/portal/tasks': typeof AuthenticatedPortalTasksRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/portal/admin/settings': typeof AuthenticatedPortalAdminSettingsRoute
  '/portal/admin/stages': typeof AuthenticatedPortalAdminStagesRoute
  '/portal/admin/users': typeof AuthenticatedPortalAdminUsersRoute
  '/portal/crm/$applicantId': typeof AuthenticatedPortalCrmApplicantIdRoute
  '/portal/admin/': typeof AuthenticatedPortalAdminIndexRoute
  '/portal/crm/': typeof AuthenticatedPortalCrmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/application-complete': typeof ApplicationCompleteRoute
  '/apply': typeof ApplyRoute
  '/evaluation': typeof EvaluationRoute
  '/login': typeof LoginRoute
  '/schedule': typeof ScheduleRoute
  '/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/portal/leaderboard': typeof AuthenticatedPortalLeaderboardRoute
  '/portal/pipeline': typeof AuthenticatedPortalPipelineRoute
  '/portal/resources': typeof AuthenticatedPortalResourcesRoute
  '/portal/tasks': typeof AuthenticatedPortalTasksRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/portal/admin/settings': typeof AuthenticatedPortalAdminSettingsRoute
  '/portal/admin/stages': typeof AuthenticatedPortalAdminStagesRoute
  '/portal/admin/users': typeof AuthenticatedPortalAdminUsersRoute
  '/portal/crm/$applicantId': typeof AuthenticatedPortalCrmApplicantIdRoute
  '/portal/admin': typeof AuthenticatedPortalAdminIndexRoute
  '/portal/crm': typeof AuthenticatedPortalCrmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/application-complete': typeof ApplicationCompleteRoute
  '/apply': typeof ApplyRoute
  '/evaluation': typeof EvaluationRoute
  '/login': typeof LoginRoute
  '/schedule': typeof ScheduleRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/_authenticated/portal/admin': typeof AuthenticatedPortalAdminRouteRouteWithChildren
  '/_authenticated/portal/crm': typeof AuthenticatedPortalCrmRouteRouteWithChildren
  '/_authenticated/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/_authenticated/portal/leaderboard': typeof AuthenticatedPortalLeaderboardRoute
  '/_authenticated/portal/pipeline': typeof AuthenticatedPortalPipelineRoute
  '/_authenticated/portal/resources': typeof AuthenticatedPortalResourcesRoute
  '/_authenticated/portal/tasks': typeof AuthenticatedPortalTasksRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/portal/admin/settings': typeof AuthenticatedPortalAdminSettingsRoute
  '/_authenticated/portal/admin/stages': typeof AuthenticatedPortalAdminStagesRoute
  '/_authenticated/portal/admin/users': typeof AuthenticatedPortalAdminUsersRoute
  '/_authenticated/portal/crm/$applicantId': typeof AuthenticatedPortalCrmApplicantIdRoute
  '/_authenticated/portal/admin/': typeof AuthenticatedPortalAdminIndexRoute
  '/_authenticated/portal/crm/': typeof AuthenticatedPortalCrmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/application-complete'
    | '/apply'
    | '/evaluation'
    | '/login'
    | '/schedule'
    | '/portal'
    | '/portal/admin'
    | '/portal/crm'
    | '/portal/calendar'
    | '/portal/leaderboard'
    | '/portal/pipeline'
    | '/portal/resources'
    | '/portal/tasks'
    | '/portal/'
    | '/portal/admin/settings'
    | '/portal/admin/stages'
    | '/portal/admin/users'
    | '/portal/crm/$applicantId'
    | '/portal/admin/'
    | '/portal/crm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/application-complete'
    | '/apply'
    | '/evaluation'
    | '/login'
    | '/schedule'
    | '/portal/calendar'
    | '/portal/leaderboard'
    | '/portal/pipeline'
    | '/portal/resources'
    | '/portal/tasks'
    | '/portal'
    | '/portal/admin/settings'
    | '/portal/admin/stages'
    | '/portal/admin/users'
    | '/portal/crm/$applicantId'
    | '/portal/admin'
    | '/portal/crm'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/application-complete'
    | '/apply'
    | '/evaluation'
    | '/login'
    | '/schedule'
    | '/_authenticated/portal'
    | '/_authenticated/portal/admin'
    | '/_authenticated/portal/crm'
    | '/_authenticated/portal/calendar'
    | '/_authenticated/portal/leaderboard'
    | '/_authenticated/portal/pipeline'
    | '/_authenticated/portal/resources'
    | '/_authenticated/portal/tasks'
    | '/_authenticated/portal/'
    | '/_authenticated/portal/admin/settings'
    | '/_authenticated/portal/admin/stages'
    | '/_authenticated/portal/admin/users'
    | '/_authenticated/portal/crm/$applicantId'
    | '/_authenticated/portal/admin/'
    | '/_authenticated/portal/crm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApplicationCompleteRoute: typeof ApplicationCompleteRoute
  ApplyRoute: typeof ApplyRoute
  EvaluationRoute: typeof EvaluationRoute
  LoginRoute: typeof LoginRoute
  ScheduleRoute: typeof ScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-complete': {
      id: '/application-complete'
      path: '/application-complete'
      fullPath: '/application-complete'
      preLoaderRoute: typeof ApplicationCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/tasks': {
      id: '/_authenticated/portal/tasks'
      path: '/tasks'
      fullPath: '/portal/tasks'
      preLoaderRoute: typeof AuthenticatedPortalTasksRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/resources': {
      id: '/_authenticated/portal/resources'
      path: '/resources'
      fullPath: '/portal/resources'
      preLoaderRoute: typeof AuthenticatedPortalResourcesRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/pipeline': {
      id: '/_authenticated/portal/pipeline'
      path: '/pipeline'
      fullPath: '/portal/pipeline'
      preLoaderRoute: typeof AuthenticatedPortalPipelineRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/leaderboard': {
      id: '/_authenticated/portal/leaderboard'
      path: '/leaderboard'
      fullPath: '/portal/leaderboard'
      preLoaderRoute: typeof AuthenticatedPortalLeaderboardRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/calendar': {
      id: '/_authenticated/portal/calendar'
      path: '/calendar'
      fullPath: '/portal/calendar'
      preLoaderRoute: typeof AuthenticatedPortalCalendarRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/crm': {
      id: '/_authenticated/portal/crm'
      path: '/crm'
      fullPath: '/portal/crm'
      preLoaderRoute: typeof AuthenticatedPortalCrmRouteRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/admin': {
      id: '/_authenticated/portal/admin'
      path: '/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof AuthenticatedPortalAdminRouteRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/crm/': {
      id: '/_authenticated/portal/crm/'
      path: '/'
      fullPath: '/portal/crm/'
      preLoaderRoute: typeof AuthenticatedPortalCrmIndexRouteImport
      parentRoute: typeof AuthenticatedPortalCrmRouteRoute
    }
    '/_authenticated/portal/admin/': {
      id: '/_authenticated/portal/admin/'
      path: '/'
      fullPath: '/portal/admin/'
      preLoaderRoute: typeof AuthenticatedPortalAdminIndexRouteImport
      parentRoute: typeof AuthenticatedPortalAdminRouteRoute
    }
    '/_authenticated/portal/crm/$applicantId': {
      id: '/_authenticated/portal/crm/$applicantId'
      path: '/$applicantId'
      fullPath: '/portal/crm/$applicantId'
      preLoaderRoute: typeof AuthenticatedPortalCrmApplicantIdRouteImport
      parentRoute: typeof AuthenticatedPortalCrmRouteRoute
    }
    '/_authenticated/portal/admin/users': {
      id: '/_authenticated/portal/admin/users'
      path: '/users'
      fullPath: '/portal/admin/users'
      preLoaderRoute: typeof AuthenticatedPortalAdminUsersRouteImport
      parentRoute: typeof AuthenticatedPortalAdminRouteRoute
    }
    '/_authenticated/portal/admin/stages': {
      id: '/_authenticated/portal/admin/stages'
      path: '/stages'
      fullPath: '/portal/admin/stages'
      preLoaderRoute: typeof AuthenticatedPortalAdminStagesRouteImport
      parentRoute: typeof AuthenticatedPortalAdminRouteRoute
    }
    '/_authenticated/portal/admin/settings': {
      id: '/_authenticated/portal/admin/settings'
      path: '/settings'
      fullPath: '/portal/admin/settings'
      preLoaderRoute: typeof AuthenticatedPortalAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedPortalAdminRouteRoute
    }
  }
}

interface AuthenticatedPortalAdminRouteRouteChildren {
  AuthenticatedPortalAdminSettingsRoute: typeof AuthenticatedPortalAdminSettingsRoute
  AuthenticatedPortalAdminStagesRoute: typeof AuthenticatedPortalAdminStagesRoute
  AuthenticatedPortalAdminUsersRoute: typeof AuthenticatedPortalAdminUsersRoute
  AuthenticatedPortalAdminIndexRoute: typeof AuthenticatedPortalAdminIndexRoute
}

const AuthenticatedPortalAdminRouteRouteChildren: AuthenticatedPortalAdminRouteRouteChildren =
  {
    AuthenticatedPortalAdminSettingsRoute:
      AuthenticatedPortalAdminSettingsRoute,
    AuthenticatedPortalAdminStagesRoute: AuthenticatedPortalAdminStagesRoute,
    AuthenticatedPortalAdminUsersRoute: AuthenticatedPortalAdminUsersRoute,
    AuthenticatedPortalAdminIndexRoute: AuthenticatedPortalAdminIndexRoute,
  }

const AuthenticatedPortalAdminRouteRouteWithChildren =
  AuthenticatedPortalAdminRouteRoute._addFileChildren(
    AuthenticatedPortalAdminRouteRouteChildren,
  )

interface AuthenticatedPortalCrmRouteRouteChildren {
  AuthenticatedPortalCrmApplicantIdRoute: typeof AuthenticatedPortalCrmApplicantIdRoute
  AuthenticatedPortalCrmIndexRoute: typeof AuthenticatedPortalCrmIndexRoute
}

const AuthenticatedPortalCrmRouteRouteChildren: AuthenticatedPortalCrmRouteRouteChildren =
  {
    AuthenticatedPortalCrmApplicantIdRoute:
      AuthenticatedPortalCrmApplicantIdRoute,
    AuthenticatedPortalCrmIndexRoute: AuthenticatedPortalCrmIndexRoute,
  }

const AuthenticatedPortalCrmRouteRouteWithChildren =
  AuthenticatedPortalCrmRouteRoute._addFileChildren(
    AuthenticatedPortalCrmRouteRouteChildren,
  )

interface AuthenticatedPortalRouteRouteChildren {
  AuthenticatedPortalAdminRouteRoute: typeof AuthenticatedPortalAdminRouteRouteWithChildren
  AuthenticatedPortalCrmRouteRoute: typeof AuthenticatedPortalCrmRouteRouteWithChildren
  AuthenticatedPortalCalendarRoute: typeof AuthenticatedPortalCalendarRoute
  AuthenticatedPortalLeaderboardRoute: typeof AuthenticatedPortalLeaderboardRoute
  AuthenticatedPortalPipelineRoute: typeof AuthenticatedPortalPipelineRoute
  AuthenticatedPortalResourcesRoute: typeof AuthenticatedPortalResourcesRoute
  AuthenticatedPortalTasksRoute: typeof AuthenticatedPortalTasksRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteRouteChildren: AuthenticatedPortalRouteRouteChildren =
  {
    AuthenticatedPortalAdminRouteRoute:
      AuthenticatedPortalAdminRouteRouteWithChildren,
    AuthenticatedPortalCrmRouteRoute:
      AuthenticatedPortalCrmRouteRouteWithChildren,
    AuthenticatedPortalCalendarRoute: AuthenticatedPortalCalendarRoute,
    AuthenticatedPortalLeaderboardRoute: AuthenticatedPortalLeaderboardRoute,
    AuthenticatedPortalPipelineRoute: AuthenticatedPortalPipelineRoute,
    AuthenticatedPortalResourcesRoute: AuthenticatedPortalResourcesRoute,
    AuthenticatedPortalTasksRoute: AuthenticatedPortalTasksRoute,
    AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  }

const AuthenticatedPortalRouteRouteWithChildren =
  AuthenticatedPortalRouteRoute._addFileChildren(
    AuthenticatedPortalRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalRouteRoute: typeof AuthenticatedPortalRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalRouteRoute: AuthenticatedPortalRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApplicationCompleteRoute: ApplicationCompleteRoute,
  ApplyRoute: ApplyRoute,
  EvaluationRoute: EvaluationRoute,
  LoginRoute: LoginRoute,
  ScheduleRoute: ScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
